import type { Metadata } from 'next';
import '../globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Header from '@/components/Header';
import { draftMode } from 'next/headers';
import { VisualEditing } from 'next-sanity';
import DisableDraftModeBtn from '@/components/DisableDraftModeBtn';
import { SanityLive } from '@/sanity/lib/live';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={`antialiased`}>
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftModeBtn />
              <VisualEditing />
            </>
          )}
          <main>
            <Header />
            {children}
            <SanityLive />
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
